name: Tests

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ (github.ref_name == github.event.repository.default_branch && github.run_id) || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: RSpec
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v5

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@675dd7ba1b06c8786a1480d89c384f5620a42647 # v1.281.0
        with:
          ruby-version: "3.4"
          bundler-cache: true

      - name: Run tests
        run: bundle exec rspec
